### PR TITLE
python: added detectnet-video.py and imagenet-video.py

### PR DESCRIPTION
**Pull request by aconchillo**
Added two new examples that add support for using detectnet and imagenet on
video files.

### CODE REVIEW

**Comment by aconchillo** [comment]
This PR depends on https://github.com/dusty-nv/jetson-utils/pull/10

**Comment by aconchillo** [comment]
updated the two example so closing the renderer window (if --render) also stops the example.

**Comment by dusty-nv** [comment]
Thanks @aconchillo , appreciate it.   I will merge these and your PR's for `jetson-utils` as soon as I finish making a few other modifications.

**Comment by aconchillo** [comment]
@dusty-nv absolutely. i have also updated the `jetson-utils` PR to use mapped memory instead. i assume it's hopefully the same instead of performance. the reason to not copy the frame to GPU-only memory is because of `jetson.utils.saveImageRGBA` only works with mapped memory. see https://github.com/aconchillo/jetson-utils/commit/a557a8598a41366e73077b6ddcb1d374bb742d8b#commitcomment-34771648

**Comment by maponarooo** [comment]
An error occurs at cmake ../
What is the problem?
===========================
jetson@jetson-nano:~/jetson/acon/jetson-inference/build$ cmake ../
 
Note:  this project uses git submodules in the source tree.
       if you haven't already, run the following command from
       the project's root directory:
 
           git submodule update --init


-- using patched FindCUDA.cmake
-- CUDA version: 10.0
-- CUDA 10 detected, enabling SM_72
CMake Error at CMakeLists.txt:74 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "3.0.0".

  The following configuration files were considered but not accepted:

    /usr/lib/aarch64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake, version: 4.1.1

-- Configuring incomplete, errors occurred!

**Comment by dusty-nv** [comment]
I wonder if your repo is out-of-date, because this issue was fixed for JetPack 4.3 here:

https://github.com/dusty-nv/jetson-inference/blob/8846dcb274ff812880ef7bf9d42eb1dd75c9e7b7/CMakeLists.txt#L74

**Comment by maponarooo** [comment]
> I wonder if your repo is out-of-date, because this issue was fixed for JetPack 4.3 here:
> 
> https://github.com/dusty-nv/jetson-inference/blob/8846dcb274ff812880ef7bf9d42eb1dd75c9e7b7/CMakeLists.txt#L74
I got it~
Thank you!

**Comment by bl6594** [comment]
@aconchillo Thank you for your contribution!  It is exactly what I am looking for.
But I am having difficulties to checkout your commit, and can you please help!
I cloned the repo by $git clone https://github.com/dusty-nv/jetson-inference.git
then I ran $git checkout 3cd88fcd074671690ea8cabf5138c5e7e2dc1730 
but it complained that fatal: reference is not a tree: 3cd88fcd074671690ea8cabf5138c5e7e2dc1730
Thanks!

**Comment by fauziacharuna** [comment]
hi @aconchillo sorry for my bad english, i'm very beginner in jetson inference. I was completely clone your forks repo which contain detecnet-video, but when im running in my jetson inference, error saying 'module' object has no attribute 'VideoSource'. How to solve this problem? is that the opencv must version 3? or rebuild the jetson inference? thanks for your advice.
image

**Comment by bl6594** [comment]
Not sure why you chose to use the aconchillo's version instead of main repo.  I am guessing you want to use gstreamer.  As to the cv version, I am using 4.1.1 and it seems working for me.  BTW, I tried aconchillo's version before, and found that there was a memory leak at that time, then switched back to the main repo.

**Comment by aconchillo** [comment]
I haven't played with this for a long time. I will try to revive it and get it up to date. @bl6594 does the main repo support detection non video files? if so there might not be not need to update this.

**Comment by dusty-nv** [comment]
@aconchillo the jetson-inference `dev` branch now supports video files, RTP/RTSP streams, ect from both C++ and Python.  So you may not need to update it.  I will be merging it into master as soon as I am done with documentation.   For now, see here:

https://github.com/dusty-nv/jetson-inference/blob/dev/docs/aux-streaming.md

**Comment by aconchillo** [comment]
@dusty-nv awesome! thanks!

**Pull request closed without merging**
